info:
  name: userService
  contract: 学习springCloud
server:
  port: 8765
# 配置eureka
#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 192.168.37.128
    port: 6379
    password: 123456
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
    timeout: 0
