spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat, wall, log4j
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    smtp:
      auth: true
    password: qkfrzhyugmdtijch
    port: 25
    test-connection: true
    username: 1179555783@qq.com
  redis:
    host: 192.168.237.128
    port: 6379
    password: test@2018
    jedis:
      pool:
        max-active: 20
        min-idle: 1
        max-idle: 1
    database: 0



##    freemarker静态资源配置
#
##       设定ftl文件路径
#  spring.freemarker.tempalte-loader-path=classpath:/templates
#  #        关闭缓存，及时刷新，上线生产环境需要修改为true
#  spring.freemarker.cache=false
#  spring.freemarker.charset=UTF-8
#  spring.freemarker.check-template-location=true
#  spring.freemarker.content-type=text/html
#  spring.freemarker.expose-request-attributes=true
#  spring.freemarker.expose-session-attributes=true
#  spring.freemarker.request-context-attribute=request
#  spring.freemarker.suffix=.ftl


