spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat, wall, log4j
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    smtp:
      auth: true
    password: qkfrzhyugmdtijch
    port: 25
    test-connection: true
    username: 1179555783@qq.com
  redis:
    host:
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20
        min-idle: 1
        max-idle: 1
    database: 0


